### ISSUE TITLE
-Si should have exit status 1 after fail

### ISSUE THREAD

**Issue by ghost** [Kiwi/clyde#28]
clyde -Si leaves an exit status of 0 even if it fails.

**Comment by ghost** [comment]
same for -G pkgdoesntexist imho -- see http://github.com/bruenig/packer/issues#issue/10

**Comment by OttoAllmendinger** [comment]
same as issue #30 - fixed by dea9b62ccd3debdb6fee5192756226f754cee066

**Comment by ghost** [comment]
Doesn't fix it here:
$ clyde -Si asdf
error: package 'asdf' was not found
$ echo $?
0

**Comment by OttoAllmendinger** [comment]
are you certain that you are using the fixed version from my fork?

**Comment by ghost** [comment]
Sorry, it works now.
